// Regenerates js/icons.js and js/geo-data.js.
// Run from the greenrah-pitch folder:  node tools/gen-data.mjs [path-to-@tabler/icons]
// Inputs:
//   @tabler/icons (MIT) outline SVGs, default ../../GreenRah/node_modules/@tabler/icons
//   tools/cache/ne50.geojson      Natural Earth 1:50m admin 0 countries (public domain)
//   tools/cache/freguesias.geojson Lisbon parish outlines (from the GreenRah repo)
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const tablerDir = process.argv[2] || path.resolve(root, '..', '..', 'GreenRah', 'node_modules', '@tabler', 'icons');

/* ---------------- icons ---------------- */

const ICONS = [
  'sun', 'sunrise', 'sunset', 'moon', 'temperature', 'droplet', 'wind', 'building', 'mountain', 'route', 'walk',
  'wheelchair', 'stairs', 'map-pin', 'map-2', 'clock', 'calendar', 'share', 'language', 'brand-android',
  'brand-apple', 'device-mobile', 'device-laptop', 'world', 'users', 'building-community', 'trees',
  'heart-handshake', 'chart-bar', 'rocket', 'mail', 'engine', 'gauge', 'arrow-right', 'check', 'x',
  'minus', 'toilet-paper', 'user', 'luggage', 'old', 'baby-carriage', 'search', 'current-location',
  'arrows-exchange', 'coin-euro', 'building-bank', 'flag', 'qrcode', 'info-circle', 'keyboard',
  'player-play', 'player-pause', 'refresh', 'chevron-left', 'chevron-right', 'layout-grid',
  'maximize', 'help', 'contrast', 'accessible', 'leaf', 'heartbeat', 'presentation', 'microphone-2',
  'circle-check', 'progress', 'eye-off', 'world-www', 'id-badge-2', 'bolt', 'shield-check', 'sparkles'
];

const icons = {};
const missing = [];
for (const name of ICONS) {
  const file = path.join(tablerDir, 'icons', 'outline', `${name}.svg`);
  if (!fs.existsSync(file)) { missing.push(name); continue; }
  const svg = fs.readFileSync(file, 'utf8');
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/<path stroke="none" d="M0 0h24v24H0z" fill="none"\s*\/>/, '')
    .replace(/\s+/g, ' ')
    .trim();
  icons[name] = inner;
}
if (missing.length) console.warn('Missing Tabler icons:', missing.join(', '));
const tablerVersion = JSON.parse(fs.readFileSync(path.join(tablerDir, 'package.json'), 'utf8')).version;
fs.writeFileSync(
  path.join(root, 'js', 'icons.js'),
  `/* Tabler Icons v${tablerVersion} (MIT, https://tabler.io/icons), outline style.\n   Generated by tools/gen-data.mjs. Inlined so the deck works offline. */\nwindow.GR_ICONS = ${JSON.stringify(icons, null, 0).replace(/","/g, '",\n"')};\n`
);
console.log(`icons: ${Object.keys(icons).length} written`);

/* ---------------- geometry helpers ---------------- */

function simplify(points, tol) {
  // Douglas Peucker on projected points; closed rings are split in two halves
  if (points.length < 4) return points;
  const f = points[0]; const l = points[points.length - 1];
  if (f[0] === l[0] && f[1] === l[1]) {
    const mid = Math.floor(points.length / 2);
    return simplifyOpen(points.slice(0, mid + 1), tol).concat(simplifyOpen(points.slice(mid), tol).slice(1));
  }
  return simplifyOpen(points, tol);
}

function simplifyOpen(points, tol) {
  if (points.length < 3) return points;
  const keep = new Uint8Array(points.length);
  keep[0] = keep[points.length - 1] = 1;
  const stack = [[0, points.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    let maxD = 0; let idx = -1;
    const [ax, ay] = points[a]; const [bx, by] = points[b];
    const dx = bx - ax; const dy = by - ay; const len = Math.hypot(dx, dy) || 1e-9;
    for (let i = a + 1; i < b; i++) {
      const d = Math.abs(dy * points[i][0] - dx * points[i][1] + bx * ay - by * ax) / len;
      if (d > maxD) { maxD = d; idx = i; }
    }
    if (maxD > tol && idx > 0) { keep[idx] = 1; stack.push([a, idx], [idx, b]); }
  }
  return points.filter((_, i) => keep[i]);
}

function ringToPath(ring) {
  return 'M' + ring.map((p) => `${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join('L') + 'Z';
}

/* ---------------- Europe map (Lambert azimuthal equal area, EU standard centre) ---------------- */

const EU = ['AUT', 'BEL', 'BGR', 'HRV', 'CYP', 'CZE', 'DNK', 'EST', 'FIN', 'FRA', 'DEU', 'GRC', 'HUN', 'IRL', 'ITA',
  'LVA', 'LTU', 'LUX', 'MLT', 'NLD', 'POL', 'PRT', 'ROU', 'SVK', 'SVN', 'ESP', 'SWE', 'ALD'];
const COVERED = new Set([...EU, 'GBR']);

const lam0 = 10 * Math.PI / 180; const phi0 = 52 * Math.PI / 180;
function laea(lon, lat) {
  const l = lon * Math.PI / 180; const p = lat * Math.PI / 180;
  const k = Math.sqrt(2 / (1 + Math.sin(phi0) * Math.sin(p) + Math.cos(phi0) * Math.cos(p) * Math.cos(l - lam0)));
  return [k * Math.cos(p) * Math.sin(l - lam0), -k * (Math.cos(phi0) * Math.sin(p) - Math.sin(phi0) * Math.cos(p) * Math.cos(l - lam0))];
}

// frame: from west of Portugal to the Black Sea, north Africa coast to north Scandinavia
const frameGeo = [[-12, 35], [-11, 60], [36, 34], [42, 58], [28, 71.5], [5, 71.5], [-12, 52], [30, 35], [14, 34.8], [25, 34.3], [-15, 38.5]];
const fp = frameGeo.map(([a, b]) => laea(a, b));
const fx0 = Math.min(...fp.map((p) => p[0])); const fx1 = Math.max(...fp.map((p) => p[0]));
const fy0 = Math.min(...fp.map((p) => p[1])); const fy1 = Math.max(...fp.map((p) => p[1]));
const EW = 900; const scale = EW / (fx1 - fx0); const EH = Math.round((fy1 - fy0) * scale);
const toEU = (lon, lat) => { const [x, y] = laea(lon, lat); return [(x - fx0) * scale, (y - fy0) * scale]; };

const ne = JSON.parse(fs.readFileSync(path.join(root, 'tools', 'cache', 'ne50.geojson'), 'utf8'));
const seen = []; const europe = { width: EW, height: EH, covered: [], other: [], lisbon: toEU(-9.14, 38.72).map((v) => +v.toFixed(1)) };
for (const f of ne.features) {
  const code = f.properties.ADM0_A3;
  const g = f.geometry; if (!g) continue;
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
  const parts = [];
  for (const poly of polys) {
    for (const ring of poly) {
      if (ring.some(([lon, lat]) => lon < -40 || lon > 75 || lat < 25)) {
        // skip rings far outside the frame (overseas territories, Asia)
        if (!ring.some(([lon, lat]) => lon > -30 && lon < 60 && lat > 30 && lat < 75)) continue;
      }
      const pts = ring.map(([lon, lat]) => toEU(lon, lat));
      const xs = pts.map((p) => p[0]); const ys = pts.map((p) => p[1]);
      if (Math.max(...xs) < -20 || Math.min(...xs) > EW + 20 || Math.max(...ys) < -20 || Math.min(...ys) > EH + 20) continue;
      let s = simplify(pts, 0.7);
      if (s.length < 4 && COVERED.has(code)) s = pts; // keep small covered islands such as Malta
      if (s.length < 4) continue;
      parts.push(ringToPath(s));
    }
  }
  if (!parts.length) continue;
  (COVERED.has(code) ? europe.covered : europe.other).push(parts.join('')); if (COVERED.has(code)) seen.push(code);
}

/* ---------------- Lisbon parishes + illustrative grid ---------------- */

const fr = JSON.parse(fs.readFileSync(path.join(root, 'tools', 'cache', 'freguesias.geojson'), 'utf8'));
let minLon = 180; let maxLon = -180; let minLat = 90; let maxLat = -90;
const allRings = [];
for (const f of fr.features) {
  const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
  for (const poly of polys) {
    allRings.push(poly[0]);
    for (const [lon, lat] of poly[0]) {
      minLon = Math.min(minLon, lon); maxLon = Math.max(maxLon, lon);
      minLat = Math.min(minLat, lat); maxLat = Math.max(maxLat, lat);
    }
  }
}
const kx = Math.cos(38.74 * Math.PI / 180);
const LW = 900; const lscale = LW / ((maxLon - minLon) * kx); const LH = Math.round((maxLat - minLat) * lscale);
const toL = (lon, lat) => [(lon - minLon) * kx * lscale, (maxLat - lat) * lscale];
const ringsL = allRings.map((r) => r.map(([a, b]) => toL(a, b)));
function pointInRing(ring, [x, y]) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i]; const [xj, yj] = ring[j];
    if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}
const CELL = 26;
const cells = [];
// Illustrative values only: smooth blobs + noise. NOT real city data.
const blobs = [[0.62, 0.72, 0.16], [0.35, 0.45, 0.12], [0.78, 0.35, 0.14], [0.2, 0.8, 0.1], [0.5, 0.2, 0.1]];
function hash(i, j) { const v = Math.sin(i * 12.9898 + j * 78.233) * 43758.5453; return v - Math.floor(v); }
for (let j = 0; j * CELL < LH; j++) {
  for (let i = 0; i * CELL < LW; i++) {
    const c = [i * CELL + CELL / 2, j * CELL + CELL / 2];
    if (!ringsL.some((r) => pointInRing(r, c))) continue;
    const u = c[0] / LW; const v = c[1] / LH;
    let val = 0;
    for (const [bx, by, br] of blobs) val += Math.exp(-((u - bx) ** 2 + (v - by) ** 2) / (2 * br * br));
    val = Math.min(1, val * 0.75 + hash(i, j) * 0.25);
    cells.push([i, j, +val.toFixed(2)]);
  }
}
const lisbon = {
  width: LW, height: LH, cell: CELL,
  parishes: ringsL.map((r) => ringToPath(simplify(r, 0.8))),
  cells
};

fs.writeFileSync(
  path.join(root, 'js', 'geo-data.js'),
  `/* Map data for the pitch. Generated by tools/gen-data.mjs.\n   Europe: Natural Earth 1:50m admin 0 countries (public domain), Lambert azimuthal equal area.\n   Lisbon: parish outlines (freguesias). Grid values are ILLUSTRATIVE, not real city data. */\nwindow.GR_GEO = ${JSON.stringify({ europe, lisbon })};\n`
);
console.log('covered missing:', [...COVERED].filter((c) => !seen.includes(c))); console.log(`europe: ${EW}x${EH}, covered ${europe.covered.length}, other ${europe.other.length}; lisbon ${LW}x${LH}, cells ${cells.length}`);
